server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog?useUnicode=true&charactorEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: banyuan
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      repositories:
        enabled: true

mybatis:
  mapper-locations: classpath:com/banyuan/blog/mapper/*.xml
  config-location: classpath:config/mybatis.xml

security:
  permittedurls:
    urls:
        - /login
        - /index
        - /static/**
        - /**/*.*
        - /webjars/**

jwt:
  secret: dafsfsafdsa
  expiration: 1209600000
  tokenHeader: Athentication
  tokenHead: bearer