server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog?useUnicode=true&charactorEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: banyuan
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/banyuan/blog/dao/*.xml
  config-location: classpath:config/mybatis.xml